### ISSUE TITLE
trouble 'finding' GE J85 (F5jet) engine with AJE & AJEx

### ISSUE THREAD

**Issue by Growflavor** [seanyoung247/AJEExtended#2]
Hi!  Thank you for creating these configs. I look forward to learning from them regarding more 'realistic' engine performance in KSP flight (not having any engine experience myself in the real world)

I saw the note in the KSP forum page "Hi All. I've not forgotten this! I'm currently working on a complete overhaul using templates for the parts﻿ to try and streamline everything"

Thus, hoping what I have encountered is something already familiar to you or being worked on so you can point me in the right direction...

KSP 1.4.5
Airplane Plus - 24.0	
Advanced Jet Engine - 2.11.4 
AJEExtended v1.1.2
(& a bunch of other mods)

Was playing with KerbalX craft like these made in KSP 1.4.5 with the F5 engine (not AJE).

https://kerbalx.com/ZLM-Master/T-30G-Camo

https://kerbalx.com/ZLM-Master/T-60-AI-FAR-Training-Bot

F5jet engine works ok with the standard AirplanePlus config, but when I add AJE & AJEEx config the 'new' engine seems to only be 'partially' present....shows on the plane but without fuel and I can not find it in the KSP parts menu which is odd...

So decided my issue is not likely to just be air intake or fuel flow issues in the craft parts positions 'discovered' by adding AJE & AJEEx to GameData. 

I do not see any fuel flow at all & 0 thrust indicated in KER for the vessel & could not find the F5jet (GE J85) part in the KSP menu, plus found a forum post describing some 'no thrust' issues when colliders have problems (link provided at end of this msg along with link to screenshot album of my case)...then found some 'skipp' WRN messages in the KSP.log...so hoping all this makes much more sense to you as to what is causing my issue.

Here are the most key 3 of the WRN from the KSP.log:

`[WRN 18:36:54.674] [Part]: PartModule indexing mismatch at f5jet, index 0.
Node 'MultiModeEngine' found in loaded data, but 'FXModuleAnimateThrottle' is defined in prefab.
Looking for MultiModeEngine in other indices...
[WRN 18:36:54.674] ...no MultiModeEngine module found on part definition. Skipping...

[WRN 18:36:54.674] [Part]: PartModule indexing mismatch at f5jet, index 0.
Node 'ModuleEnginesFX' found in loaded data, but 'FXModuleAnimateThrottle' is defined in prefab.
Looking for ModuleEnginesFX in other indices...
[WRN 18:36:54.674] ...no ModuleEnginesFX module found on part definition. Skipping...

[WRN 18:36:54.674] [Part]: PartModule indexing mismatch at f5jet, index 0.
Node 'ModuleEnginesFX' found in loaded data, but 'FXModuleAnimateThrottle' is defined in prefab.
Looking for ModuleEnginesFX in other indices...
[WRN 18:36:54.674] ...no ModuleEnginesFX module found on part definition. Skipping...`

**Here is an album of screenshots & 1080p videos with additional transform info & log data & actual craft behavior with AJE & AJEEx config:**

https://photos.app.goo.gl/56eoYewYQt4oKL4C6

**closest match to this issue & symptomset I could find in the KSP forum:**

https://forum.kerbalspaceprogram.com/index.php?/topic/160682-modded-engine-has-no-thrust-in-ksp-122/

I look forward to your thoughts & thanks again for the effort & updates you are doing!

**Comment by seanyoung247** [comment]
Thanks for the report. I'm aware of the issue. It's one of the reasons I'm trying to move to a template system. For some reason I can't get it to clobber the stock multi-mode engine modules. So hopefully will be fixed in the next update.

**Comment by seanyoung247** [comment]
This should now be fixed in the latest release
